apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-app
  name: nginx-deploy
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - image: gcr.io/k8s-aksels/github-akselsledins-architecture:v0.2
        name: nginx-pod
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 50m
      restartPolicy: Always
      terminationGracePeriodSeconds: 30